AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  AccelaAutoScalingGroup
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: AccelaLNDs
      # AvailabilityZones: 
      #   - String
      CapacityRebalance: true
      # Context: String
      # Cooldown: String
      DesiredCapacity: 3
      # DesiredCapacityType: String
      # HealthCheckGracePeriod: Integer
      # HealthCheckType: String
      # InstanceId: String
      # LaunchConfigurationName: String
      LaunchTemplate: 
          LaunchTemplateId: String
          LaunchTemplateName: AccelaLaunchTemplate
          Version: String

      LifecycleHookSpecificationList: 
        - LifecycleHookSpecification
      LoadBalancerNames: 
        - String
      MaxInstanceLifetime: Integer
      MaxSize: String
      MetricsCollection: 
        - MetricsCollection
      MinSize: String
      MixedInstancesPolicy: 
        MixedInstancesPolicy
      NewInstancesProtectedFromScaleIn: Boolean
      NotificationConfigurations: 
        - NotificationConfiguration
      PlacementGroup: String
      ServiceLinkedRoleARN: String
      Tags: 
        - TagProperty
      TargetGroupARNs: 
        - String
      TerminationPolicies: 
        - String
      VPCZoneIdentifier: 
        - String
  AccelaLaunchTemplate
    Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          BlockDeviceMappings: 
            - BlockDeviceMapping
          CapacityReservationSpecification: 
            CapacityReservationSpecification
          CpuOptions: 
            CpuOptions
          CreditSpecification: 
            CreditSpecification
          DisableApiTermination: Boolean
          EbsOptimized: Boolean
          ElasticGpuSpecifications: 
            - ElasticGpuSpecification
          ElasticInferenceAccelerators: 
            - LaunchTemplateElasticInferenceAccelerator
          EnclaveOptions: 
            EnclaveOptions
          HibernationOptions: 
            HibernationOptions
          IamInstanceProfile: 
            IamInstanceProfile
          ImageId: String
          InstanceInitiatedShutdownBehavior: String
          InstanceMarketOptions: 
            InstanceMarketOptions
          InstanceRequirements: 
            InstanceRequirements
          InstanceType: String
          KernelId: String
          KeyName: String
          LicenseSpecifications: 
            - LicenseSpecification
          MetadataOptions: 
            MetadataOptions
          Monitoring: 
            Monitoring
          NetworkInterfaces: 
            - NetworkInterface
          Placement: 
            Placement
          RamDiskId: String
          SecurityGroupIds: 
            - String
          SecurityGroups: 
            - String
          TagSpecifications: 
            - TagSpecification
          UserData: String

        LaunchTemplateName: AccelaLaunchTemplate
        TagSpecifications: 
          - LaunchTemplateTagSpecification

